baseURL = "https://mengsheng.me/"
languageCode = "zh-CN"
title = "黄金之心号|博客"
publishDir = "docs"
theme = "hugo-primer"

hasCJKLanguage = true
summaryLength = 0
# Code pen
pygmentsUseClassic       = true
pygmentsCodeFences       = true
pygmentsStyle            = "autumn"


[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
description = "Describe what your web page is about"



